language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
      - gcc-6
      - g++-6
      - qt510-meta-minimal
      - cmake
matrix:
  include:
    - os: linux
      sudo: enabled
      dist: trusty
      compiler: gcc
      before_script:
        - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
        - source $QT_ENV_SCRIPT
        - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++;
    - os: osx
      compiler: clang
      install: 
        - brew install qt
        - brew install libomp
      before_script:
        - export PATH="/usr/local/opt/qt/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/qt/lib"
        - export CPPFLAGS="-I/usr/local/opt/qt/include"
script:
  - cd Source
  - mkdir build && cd build
  - cmake ..
  - make
